# Generated by Django 3.2.12 on 2022-08-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoseCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='fnac',
        ),
    ]
