# Generated by Django 3.2.12 on 2022-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseCoder', '0002_auto_20220822_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='edad',
            field=models.IntegerField(default=1),
        ),
    ]
